open Parser

let string_of_tok = function
  | INT _ -> "INT"
  | FLOAT _ -> "FLOAT"
  | ID _ -> "ID"
  | TIMES -> "TIMES"
  | DIV -> "DIV"
  | MOD -> "MOD"
  | PLUS -> "PLUS"
  | MINUS -> "MINUS"
  | LSHIFT -> "LSHIFT"
  | RSHIFT -> "RSHIFT"
  | COMMA -> "COMMA"
  | LPAREN -> "LPAREN"
  | RPAREN -> "RPAREN"
  | LBRACE -> "LBRACE"
  | RBRACE -> "RBRACE"
  | LBRACKET -> "LBRACKET"
  | RBRACKET -> "RBRACKET"
  | LT -> "LT"
  | LEQ -> "LEQ"
  | GT -> "GT"
  | GEQ -> "GEQ"
  | CMP_EQ -> "CMP_EQ"
  | CMP_NEQ -> "CMP_NEQ"
  | EQ -> "EQ"
  | SEMICOLON -> "SEMICOLON"
  | COLON -> "COLON"
  | NEWLINE -> "NEWLINE"
  | SPACE -> "SPACE"
  | WHILE -> "WHILE"
  | TRUE -> "TRUE"
  | TAB -> "TAB"
  | RANGE -> "RANGE"
  | PRINT -> "PRINT"
  | IN -> "IN"
  | IF -> "IF"
  | FOR -> "FOR"
  | FALSE -> "FALSE"
  | EOF -> "EOF"
  | ELSE -> "ELSE"
  | ELIF -> "ELIF"
  | DEF -> "DEF"
  | RETURN -> "RETURN"
  | INDENT -> "INDENT\n"
  | DEDENT -> "\nDEDENT"
